# Generated by Django 3.1.7 on 2021-12-02 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pymes_empresas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresas',
            name='estado',
            field=models.CharField(blank=True, default='Activo', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='empresas',
            name='ruc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='empresas',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='ciudad',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='local',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='nombre',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='provincia',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
