# Generated by Django 3.1.7 on 2022-12-02 17:48

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('central_catalogo', '0003_auto_20220216_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogo',
            name='config',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
