# Generated by Django 3.1.7 on 2021-09-21 21:16

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('marca', models.CharField(max_length=200)),
                ('imagen', models.CharField(max_length=200)),
                ('precioNormal', models.CharField(max_length=200)),
                ('presioSupermonedas', models.CharField(max_length=200)),
                ('efectivo', models.CharField(max_length=200)),
                ('codigoQR', models.CharField(max_length=200)),
                ('cantidad', models.IntegerField(null=True)),
                ('empresa_id', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('state', models.SmallIntegerField(default=1)),
            ],
        ),
    ]
