# Generated by Django 3.1.7 on 2021-09-22 17:21

import apps.CENTRAL.central_productos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_productos', '0002_auto_20210921_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to=apps.CENTRAL.central_productos.models.upload_path),
        ),
    ]
