# Generated by Django 3.1.7 on 2021-09-22 16:48

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('identificacion', models.CharField(max_length=200)),
                ('nombres', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=200)),
                ('genero', models.CharField(max_length=200)),
                ('fechaNacimiento', models.DateField(null=True)),
                ('edad', models.SmallIntegerField(null=True)),
                ('ciudad', models.CharField(max_length=200, null=True)),
                ('provincia', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('emailAdicional', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('whatsapp', models.CharField(max_length=150, null=True)),
                ('facebook', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('instagram', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('twitter', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('tiktok', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('youtube', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('imagen', models.FileField(blank=True, null=True, upload_to='media/')),
                ('user_id', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('state', models.SmallIntegerField(default=1)),
            ],
        ),
    ]
