# Generated by Django 3.1.7 on 2021-09-16 17:24

import apps.PERSONAS.personas_personas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas_personas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personas',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=apps.PERSONAS.personas_personas.models.upload_path),
        ),
    ]
