# Generated by Django 3.1.7 on 2022-05-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_monedas', '0003_auto_20220125_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monedas',
            name='tipo',
            field=models.CharField(choices=[('Supermonedas', 'Supermonedas'), ('Recompensa', 'Recompensa'), ('Pago', 'Pago'), ('Cobros', 'Cobros'), ('Descuentos', 'Descuentos'), ('Acumulación', 'Acumulacion'), ('Consumo', 'Comsumo'), ('Otro', 'Otro')], default='Otro', max_length=255),
        ),
        migrations.AlterField(
            model_name='monedas',
            name='user_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
